### ISSUE TITLE
Phaser as dev dependency?

### ISSUE THREAD

**Issue by 16patsle** [samme/phaser-component-health#1]
I noticed that Phaser is set as a dependency of this package. Is this necessary? This causes npm installs to download a separate copy of Phaser for this plugin, which never ends up getting used if you use this package as a dependency. The only places where the Phaser package is used directly seems to be in the tests and the demo, while the src just uses the Phaser global.

I'd say Phaser makes more sense as a dev dependency. Additionally, the phaser package could be added as a peer dependency to force a specific minimum version of Phaser for dependents.

**Comment by samme** [comment]
I think you're right that it should probably be a peer dependency instead.
